import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut,setPersistence,browserLocalPersistence} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,addDoc,collection,onSnapshot,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const $=id=>document.getElementById(id);
const CATS=['Все','Продукты','Соусы и специи','Упаковка','Расходники'];
const defaults=[
  ['Авокадо','кг','Продукты'],['Ананас','кг','Продукты'],['Бекон','кг','Продукты'],['Булочка для бургера 100 мм','шт','Продукты'],['Булочка для бургера 125 мм','шт','Продукты'],['Булочка чёрная 125 мм','шт','Продукты'],['Ветчина','кг','Продукты'],['Горгонзола','кг','Продукты'],['Груша','кг','Продукты'],['Дикий лосось','кг','Продукты'],['Дрожжи сырые','кг','Продукты'],['Зелёный лук','кг','Продукты'],['Икра красная','кг','Продукты'],['Икра масаго красная','кг','Продукты'],['Икра масаго оранжевая','кг','Продукты'],['Имбирь маринованный','кг','Продукты'],['Каперсы','кг','Продукты'],['Капуста белокочанная','кг','Продукты'],['Картофель','кг','Продукты'],['Картофель фри','кг','Продукты'],['Колбаски ассорти','шт','Продукты'],['Колбаски охотничьи','кг','Продукты'],['Креветка','шт','Продукты'],['Креветка для пиццы','кг','Продукты'],['Куриное филе','кг','Продукты'],['Лосось','кг','Продукты'],['Лук красный','кг','Продукты'],['Лук репчатый','кг','Продукты'],['Маслины','кг','Продукты'],['Мёд','кг','Продукты'],['Морковь','кг','Продукты'],['Моцарелла','кг','Продукты'],['Мука Семола','кг','Продукты'],['Мука пшеничная','кг','Продукты'],['Наггетсы куриные','кг','Продукты'],['Нори','шт','Продукты'],['Огурцы маринованные','кг','Продукты'],['Огурцы свежие','кг','Продукты'],['Палочки сырные в панировке','кг','Продукты'],['Панировочные сухари','кг','Продукты'],['Пепперони','кг','Продукты'],['Перец сладкий','кг','Продукты'],['Петрушка','кг','Продукты'],['Помидоры','кг','Продукты'],['Рис для суши','кг','Продукты'],['Салат листовой','кг','Продукты'],['Салат чука','кг','Продукты'],['Свёкла','кг','Продукты'],['Сельдь','кг','Продукты'],['Сливки 33%','л','Продукты'],['Сметана','кг','Продукты'],['Снежный краб','кг','Продукты'],['Сыр Гауда','кг','Продукты'],['Сыр Пармезан','кг','Продукты'],['Сыр плавленый','кг','Продукты'],['Сыр творожный','кг','Продукты'],['Сыр Чеддер','кг','Продукты'],['Томаты черри','кг','Продукты'],['Тортилья сырная','шт','Продукты'],['Фарш говяжий','кг','Продукты'],['Фарш куриный','кг','Продукты'],['Халапеньо','кг','Продукты'],['Чеснок','кг','Продукты'],['Шампиньоны','кг','Продукты'],['Яйцо куриное','шт','Продукты'],
  ['Аджика табаджан','кг','Соусы и специи'],['Васаби сухая','кг','Соусы и специи'],['Горчица зернистая','кг','Соусы и специи'],['Кетчуп','кг','Соусы и специи'],['Кориандр','кг','Соусы и специи'],['Крахмал кукурузный','кг','Соусы и специи'],['Кунжут белый','кг','Соусы и специи'],['Кунжут чёрный','кг','Соусы и специи'],['Кунжутное масло','л','Соусы и специи'],['Лавровый лист','кг','Соусы и специи'],['Майонез','кг','Соусы и специи'],['Масло оливковое','л','Соусы и специи'],['Масло подсолнечное','л','Соусы и специи'],['Масло фритюрное','л','Соусы и специи'],['Орегано сушёный','кг','Соусы и специи'],['Паприка','кг','Соусы и специи'],['Перец красный острый молотый','кг','Соусы и специи'],['Перец чёрный душистый','шт','Соусы и специи'],['Перец чёрный молотый','кг','Соусы и специи'],['Сахар','кг','Соусы и специи'],['Соевый соус','л','Соусы и специи'],['Соль каменная','кг','Соусы и специи'],['Соль морская','кг','Соусы и специи'],['Соль экстра','кг','Соусы и специи'],['Соус барбекю','кг','Соусы и специи'],['Соус Вустерский','л','Соусы и специи'],['Соус горчичный','кг','Соусы и специи'],['Соус для пиццы томатный','кг','Соусы и специи'],['Соус кимчи','кг','Соусы и специи'],['Соус кунжутный','кг','Соусы и специи'],['Соус сладкий чили','кг','Соусы и специи'],['Соус Шрирача','кг','Соусы и специи'],['Соус Унаги','л','Соусы и специи'],['Темпурная смесь','кг','Соусы и специи'],['Темпурные сухари','кг','Соусы и специи'],['Уксус 9%','л','Соусы и специи'],['Уксус рисовый','л','Соусы и специи'],['Уксус яблочный','л','Соусы и специи'],['Усилитель вкуса','кг','Соусы и специи'],
  ['Контейнер круглый чёрный с крышкой','шт','Упаковка'],['Контейнер круглый прозрачный с крышкой','шт','Упаковка'],['Контейнер прямоугольный прозрачный','шт','Упаковка'],['Контейнер прямоугольный чёрный с крышкой','шт','Упаковка'],['Контейнер секционный прозрачный','шт','Упаковка'],['Контейнер суши чёрный с прозрачной крышкой','шт','Упаковка'],['Бокс бумажный малый','шт','Упаковка'],['Бокс бумажный большой','шт','Упаковка'],['Коробка для картофеля фри','шт','Упаковка'],['Коробка крафт для бургера','шт','Упаковка'],['Лоток алюминиевый','шт','Упаковка'],['Крышка картонная для алюминиевого лотка','шт','Упаковка'],['Пакет крафт бумажный','шт','Упаковка'],['Бумага упаковочная брендированная','шт','Упаковка'],['Стакан пластиковый малый','шт','Упаковка'],['Стакан пластиковый большой','шт','Упаковка'],
  ['Перчатки одноразовые','уп','Расходники'],['Пакет фасовочный','уп','Расходники'],['Плёнка пищевая малая','рул','Расходники'],['Плёнка пищевая большая','рул','Расходники'],['Фольга малая','рул','Расходники'],['Фольга большая','рул','Расходники'],['Пергамент для выпечки','рул','Расходники'],['Салфетки','уп','Расходники'],['Палочки для суши','уп','Расходники']
].map((x,i)=>({id:`base-${i+1}`,name:x[0],unit:x[1],category:x[2],target:0,actual:null,custom:false}));

let auth,db,user,items=[],category='Все',saveTimer,applyingRemote=false;
const cleanNumber=value=>{const n=Number(String(value).replace(',','.'));return Number.isFinite(n)&&n>=0?n:0;};
const missing=item=>Math.max(0,cleanNumber(item.target)-cleanNumber(item.actual));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultShiftName=()=>`${new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium'}).format(new Date())} — ${new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date())}`;

function renderCategories(){ $('categories').innerHTML=CATS.map(c=>`<button class="chip ${c===category?'active':''}" data-cat="${c}">${c}</button>`).join('');$('categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategories();render();}); }
function render(){
  const term=$('search').value.trim().toLowerCase(),only=$('onlyMissing').checked;
  const filtered=items.filter(i=>(category==='Все'||i.category===category)&&i.name.toLowerCase().includes(term)&&(!only||missing(i)>0));
  $('list').innerHTML=filtered.length?filtered.map(i=>`<article class="item ${missing(i)>0?'missing':''}" data-id="${i.id}"><div class="item-top"><div class="item-title"><b>${esc(i.name)}</b><small>${esc(i.category)} · ${esc(i.unit)}</small></div>${i.custom?'<button class="delete" title="Удалить">×</button>':''}</div><div class="values"><label>ДОЛЖНО БЫТЬ<input class="target" inputmode="decimal" type="number" min="0" step="0.001" value="${i.target??0}"></label><label>ЕСТЬ СЕЙЧАС<input class="actual" inputmode="decimal" type="number" min="0" step="0.001" value="${i.actual??''}" placeholder="0"></label><div class="diff">${missing(i)>0?`−${fmt(missing(i))} ${i.unit}`:'✓ хватает'}</div></div></article>`).join(''):'<div class="empty">Ничего не найдено</div>';
  $('list').querySelectorAll('.item').forEach(card=>{const item=items.find(x=>x.id===card.dataset.id);card.querySelector('.target').oninput=e=>updateValue(item,'target',e.target.value);card.querySelector('.actual').oninput=e=>updateValue(item,'actual',e.target.value);card.querySelector('.delete')?.addEventListener('click',()=>{if(confirm(`Удалить «${item.name}»?`)){items=items.filter(x=>x.id!==item.id);queueSave();render();}});});
  const needs=items.filter(i=>missing(i)>0).sort((a,b)=>b.category.localeCompare(a.category)||a.name.localeCompare(b.name));
  $('allCount').textContent=items.length;$('missingCount').textContent=needs.length;$('okCount').textContent=items.filter(i=>cleanNumber(i.target)>0&&missing(i)===0).length;
  $('needList').innerHTML=needs.length?needs.map(i=>`<div class="need"><b>${esc(i.name)}</b><b>${fmt(missing(i))} ${esc(i.unit)}</b></div>`).join(''):'<div class="empty">Всё в достатке — покупать ничего не нужно</div>';
}
function fmt(n){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);}
function updateValue(item,key,value){item[key]=value===''?null:cleanNumber(value);queueSave();renderSummaryOnly();}
function renderSummaryOnly(){
  document.querySelectorAll('.item').forEach(card=>{const i=items.find(x=>x.id===card.dataset.id);if(!i)return;card.classList.toggle('missing',missing(i)>0);card.querySelector('.diff').textContent=missing(i)>0?`−${fmt(missing(i))} ${i.unit}`:'✓ хватает';});
  const needs=items.filter(i=>missing(i)>0);$('missingCount').textContent=needs.length;$('okCount').textContent=items.filter(i=>cleanNumber(i.target)>0&&missing(i)===0).length;$('needList').innerHTML=needs.length?needs.map(i=>`<div class="need"><b>${esc(i.name)}</b><b>${fmt(missing(i))} ${esc(i.unit)}</b></div>`).join(''):'<div class="empty">Всё в достатке — покупать ничего не нужно</div>';
}
function queueSave(){clearTimeout(saveTimer);$('saveStatus').textContent='Сохраняем…';saveTimer=setTimeout(saveCurrent,450);}
async function saveCurrent(){if(!user||applyingRemote)return;try{await setDoc(doc(db,'kitchen','current'),{items,shiftName:$('shiftName').value,updatedAt:serverTimestamp(),updatedBy:user.email||user.displayName||user.uid});$('saveStatus').textContent='Сохранено в Firebase';setTimeout(()=>$('saveStatus').textContent='',1600);}catch(e){$('saveStatus').textContent=`Ошибка: ${e.message}`;}}
async function initInventory(){const ref=doc(db,'kitchen','current');const first=await getDoc(ref);if(!first.exists()){items=structuredClone(defaults);$('shiftName').value=defaultShiftName();await saveCurrent();}onSnapshot(ref,snap=>{if(!snap.exists())return;applyingRemote=true;const data=snap.data();items=Array.isArray(data.items)?data.items:structuredClone(defaults);$('shiftName').value=data.shiftName||defaultShiftName();render();applyingRemote=false;},e=>$('saveStatus').textContent=`Firebase: ${e.message}`);}
async function saveShift(){const snapshot=items.map(i=>({...i,target:cleanNumber(i.target),actual:cleanNumber(i.actual),missing:missing(i)}));try{$('saveShift').disabled=true;$('saveStatus').textContent='Сохраняем смену…';await addDoc(collection(db,'kitchenShifts'),{items:snapshot,createdAt:serverTimestamp(),createdBy:user.email||user.displayName||user.uid,shiftName:$('shiftName').value,missingCount:snapshot.filter(i=>i.missing>0).length});$('saveStatus').textContent='Смена сохранена. Результат зафиксирован.';}catch(e){$('saveStatus').textContent=`Ошибка: ${e.message}`;}finally{$('saveShift').disabled=false;}}

async function main(){const config=await fetch('/__/firebase/init.json').then(r=>r.json());const firebase=initializeApp(config);auth=getAuth(firebase);db=getFirestore(firebase);await setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,async current=>{user=current;if(!current){$('auth').classList.remove('hidden');$('app').classList.add('hidden');return;}$('auth').classList.add('hidden');$('app').classList.remove('hidden');renderCategories();await initInventory();});$('googleLogin').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){$('authError').textContent=e.code==='auth/unauthorized-domain'?'Добавьте tyuzarplata-product.web.app в Authorized domains.':'Не удалось войти через Google.';}};$('logout').onclick=()=>signOut(auth);$('search').oninput=render;$('onlyMissing').onchange=render;$('shiftName').onchange=queueSave;$('newShift').onclick=()=>{if(confirm('Начать новую смену? Поля «Есть сейчас» очистятся.')){items.forEach(i=>i.actual=null);$('shiftName').value=defaultShiftName();queueSave();render();}};$('saveShift').onclick=saveShift;$('copyResult').onclick=async()=>{const lines=items.filter(i=>missing(i)>0).map(i=>`${i.name} — ${fmt(missing(i))} ${i.unit}`);await navigator.clipboard.writeText(lines.length?`НУЖНО ПОЛУЧИТЬ:\n${lines.join('\n')}`:'Всё в достатке');$('copyResult').textContent='Скопировано';setTimeout(()=>$('copyResult').textContent='Копировать',1200);};$('addItem').onclick=()=>$('itemDialog').showModal();$('cancelItem').onclick=()=>$('itemDialog').close();$('itemForm').onsubmit=()=>{const name=$('itemName').value.trim();if(!name)return;items.push({id:`custom-${Date.now()}`,name,category:$('itemCategory').value,unit:$('itemUnit').value,target:cleanNumber($('itemTarget').value),actual:null,custom:true});$('itemForm').reset();queueSave();render();};}
main().catch(e=>{$('authError').textContent=e.message;});
