import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getFirestore,doc,getDoc,setDoc,addDoc,collection,onSnapshot,serverTimestamp,query,orderBy,limit,getDocs} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const $=id=>document.getElementById(id);
const CATS=['Все','Продукты','Соусы и специи','Упаковка','Расходники'];
const defaults=[
  ['Авокадо','кг','Продукты'],['Ананас','кг','Продукты'],['Бекон','кг','Продукты'],['Булочка для бургера 100 мм','шт','Продукты'],['Булочка для бургера 125 мм','шт','Продукты'],['Булочка чёрная 125 мм','шт','Продукты'],['Ветчина','кг','Продукты'],['Горгонзола','кг','Продукты'],['Груша','кг','Продукты'],['Дикий лосось','кг','Продукты'],['Дрожжи сырые','кг','Продукты'],['Зелёный лук','кг','Продукты'],['Икра красная','кг','Продукты'],['Икра масаго красная','кг','Продукты'],['Икра масаго оранжевая','кг','Продукты'],['Имбирь маринованный','кг','Продукты'],['Каперсы','кг','Продукты'],['Капуста белокочанная','кг','Продукты'],['Картофель','кг','Продукты'],['Картофель фри','кг','Продукты'],['Колбаски ассорти','шт','Продукты'],['Колбаски охотничьи','кг','Продукты'],['Креветка','шт','Продукты'],['Креветка для пиццы','кг','Продукты'],['Куриное филе','кг','Продукты'],['Лосось','кг','Продукты'],['Лук красный','кг','Продукты'],['Лук репчатый','кг','Продукты'],['Маслины','кг','Продукты'],['Мёд','кг','Продукты'],['Морковь','кг','Продукты'],['Моцарелла','кг','Продукты'],['Мука Семола','кг','Продукты'],['Мука пшеничная','кг','Продукты'],['Наггетсы куриные','кг','Продукты'],['Нори','шт','Продукты'],['Огурцы маринованные','кг','Продукты'],['Огурцы свежие','кг','Продукты'],['Палочки сырные в панировке','кг','Продукты'],['Панировочные сухари','кг','Продукты'],['Пепперони','кг','Продукты'],['Перец сладкий','кг','Продукты'],['Петрушка','кг','Продукты'],['Помидоры','кг','Продукты'],['Рис для суши','кг','Продукты'],['Салат листовой','кг','Продукты'],['Салат чука','кг','Продукты'],['Свёкла','кг','Продукты'],['Сельдь','кг','Продукты'],['Сливки 33%','л','Продукты'],['Сметана','кг','Продукты'],['Снежный краб','кг','Продукты'],['Сыр Гауда','кг','Продукты'],['Сыр Пармезан','кг','Продукты'],['Сыр плавленый','кг','Продукты'],['Сыр творожный','кг','Продукты'],['Сыр Чеддер','кг','Продукты'],['Томаты черри','кг','Продукты'],['Тортилья сырная','шт','Продукты'],['Фарш говяжий','кг','Продукты'],['Фарш куриный','кг','Продукты'],['Халапеньо','кг','Продукты'],['Чеснок','кг','Продукты'],['Шампиньоны','кг','Продукты'],['Яйцо куриное','шт','Продукты'],
  ['Аджика табаджан','кг','Соусы и специи'],['Васаби сухая','кг','Соусы и специи'],['Горчица зернистая','кг','Соусы и специи'],['Кетчуп','кг','Соусы и специи'],['Кориандр','кг','Соусы и специи'],['Крахмал кукурузный','кг','Соусы и специи'],['Кунжут белый','кг','Соусы и специи'],['Кунжут чёрный','кг','Соусы и специи'],['Кунжутное масло','л','Соусы и специи'],['Лавровый лист','кг','Соусы и специи'],['Майонез','кг','Соусы и специи'],['Масло оливковое','л','Соусы и специи'],['Масло подсолнечное','л','Соусы и специи'],['Масло фритюрное','л','Соусы и специи'],['Орегано сушёный','кг','Соусы и специи'],['Паприка','кг','Соусы и специи'],['Перец красный острый молотый','кг','Соусы и специи'],['Перец чёрный душистый','шт','Соусы и специи'],['Перец чёрный молотый','кг','Соусы и специи'],['Сахар','кг','Соусы и специи'],['Соевый соус','л','Соусы и специи'],['Соль каменная','кг','Соусы и специи'],['Соль морская','кг','Соусы и специи'],['Соль экстра','кг','Соусы и специи'],['Соус барбекю','кг','Соусы и специи'],['Соус Вустерский','л','Соусы и специи'],['Соус горчичный','кг','Соусы и специи'],['Соус для пиццы томатный','кг','Соусы и специи'],['Соус кимчи','кг','Соусы и специи'],['Соус кунжутный','кг','Соусы и специи'],['Соус сладкий чили','кг','Соусы и специи'],['Соус Шрирача','кг','Соусы и специи'],['Соус Унаги','л','Соусы и специи'],['Темпурная смесь','кг','Соусы и специи'],['Темпурные сухари','кг','Соусы и специи'],['Уксус 9%','л','Соусы и специи'],['Уксус рисовый','л','Соусы и специи'],['Уксус яблочный','л','Соусы и специи'],['Усилитель вкуса','кг','Соусы и специи'],
  ['Контейнер круглый чёрный с крышкой','шт','Упаковка'],['Контейнер круглый прозрачный с крышкой','шт','Упаковка'],['Контейнер прямоугольный прозрачный','шт','Упаковка'],['Контейнер прямоугольный чёрный с крышкой','шт','Упаковка'],['Контейнер секционный прозрачный','шт','Упаковка'],['Контейнер суши чёрный с прозрачной крышкой','шт','Упаковка'],['Бокс бумажный малый','шт','Упаковка'],['Бокс бумажный большой','шт','Упаковка'],['Коробка для картофеля фри','шт','Упаковка'],['Коробка крафт для бургера','шт','Упаковка'],['Лоток алюминиевый','шт','Упаковка'],['Крышка картонная для алюминиевого лотка','шт','Упаковка'],['Пакет крафт бумажный','шт','Упаковка'],['Бумага упаковочная брендированная','шт','Упаковка'],['Стакан пластиковый малый','шт','Упаковка'],['Стакан пластиковый большой','шт','Упаковка'],
  ['Перчатки одноразовые','уп','Расходники'],['Пакет фасовочный','уп','Расходники'],['Плёнка пищевая малая','рул','Расходники'],['Плёнка пищевая большая','рул','Расходники'],['Фольга малая','рул','Расходники'],['Фольга большая','рул','Расходники'],['Пергамент для выпечки','рул','Расходники'],['Салфетки','уп','Расходники'],['Палочки для суши','уп','Расходники']
].map((x,i)=>({id:`base-${i+1}`,name:x[0],unit:x[1],category:x[2],target:0,actual:null,custom:false}));

let db,items=[],configItems=[],category='Все',viewDay='',dayUnsub=null,configUnsub=null,dayTimer=null,configTimer=null,applyingRemote=false,history=[],onlyUnfilled=false;
const actor='Открытый доступ';
const cleanNumber=value=>{const n=Number(String(value??'').replace(',','.'));return Number.isFinite(n)&&n>=0?n:0;};
const missing=item=>Math.max(0,cleanNumber(item.target)-cleanNumber(item.actual));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const isToday=()=>viewDay===dayKey();
const defaultShiftName=()=>`${new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium'}).format(new Date())} — ${new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date())}`;
const nextMidnight=()=>{const d=new Date();d.setHours(24,0,0,0);return d;};
const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);
const snapshotItem=i=>({id:i.id,name:i.name,unit:i.unit,category:i.category,target:cleanNumber(i.target),actual:i.actual===null?null:cleanNumber(i.actual),custom:!!i.custom});

function iconIndex(item){const n=item.name.toLowerCase();if(item.category==='Упаковка'){if(n.includes('круглый чёр'))return 8;if(n.includes('круглый прозрач'))return 9;if(n.includes('прямоугольный прозрач')||n.includes('секцион'))return 10;if(n.includes('суши')||n.includes('прямоугольный чёр'))return 11;if(n.includes('фри'))return 13;if(n.includes('алюмини')||n.includes('крышка картон'))return 14;if(n.includes('бокс')||n.includes('бургер'))return 12;return 15;}if(item.category==='Расходники')return 15;if(item.category==='Соусы и специи')return /(перец|соль|паприк|орегано|кориандр|лавров|кунжут|сахар|крахмал)/.test(n)?7:6;if(/(сыр|сливк|сметан|моцарел|масл)/.test(n))return 1;if(/(лосос|кревет|сельд|икра|краб|нори)/.test(n))return 3;if(/(курин|говя|бекон|ветчин|фарш|колбас)/.test(n))return 2;if(/(мука|рис|крахмал|сухар)/.test(n))return 4;if(/(булоч|хлеб|тортиль)/.test(n))return 5;return 0;}
function exactIconIndex(item){const n=item.name.toLowerCase();if(n==='авокадо')return 0;if(n.includes('кревет'))return 1;if(n.includes('лосось')||n.includes('лосос'))return 2;if(n.includes('рис для суши'))return 3;if(n.includes('моцарел'))return 4;if(n.includes('помидор')||n.includes('томат'))return 5;if(n.includes('огурц')&&n.includes('свеж'))return 6;if(n.includes('лук красн'))return 7;if(n.includes('картоф'))return 8;if(n.includes('булоч'))return 9;if(n.includes('бекон'))return 10;if(n.includes('куриное филе'))return 11;if(n==='нори')return 12;if(n.includes('имбирь'))return 13;if(n.includes('васаби'))return 14;if(n.includes('чеддер'))return 15;return null;}
function iconStyle(item){const exact=exactIconIndex(item),i=exact===null?iconIndex(item):exact,x=(i%4)*100/3,y=Math.floor(i/4)*100/3,atlas=exact===null?'kitchen-inventory-atlas.webp':'exact-food-atlas.webp';return `background-image:url('./assets/${atlas}');background-position:${x}% ${y}%`;}
function renderCategories(){$('categories').innerHTML=CATS.map(c=>`<button class="chip ${c===category?'active':''}" data-cat="${c}">${c}</button>`).join('');$('categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategories();render();});}
function needHtml(needs){return needs.length?needs.map(i=>`<div class="need"><b>${esc(i.name)}</b><b>${fmt(missing(i))} ${esc(i.unit)}</b></div>`).join(''):'<div class="empty">Всё в достатке — покупать ничего не нужно</div>';}
function render(){const editable=isToday(),term=$('search').value.trim().toLowerCase(),only=$('onlyMissing').checked;const filtered=items.filter(i=>(category==='Все'||i.category===category)&&i.name.toLowerCase().includes(term)&&(!only||missing(i)>0)&&(!onlyUnfilled||i.actual===null||i.actual===''));const lock=!editable?'<div class="locked-banner">Прошедший день доступен только для просмотра. Изменения запрещены.</div>':'';$('list').innerHTML=lock+(filtered.length?filtered.map(i=>`<article class="item ${missing(i)>0?'missing':''} ${editable?'':'locked'}" data-id="${i.id}"><div class="item-top"><div class="thumb" style="${iconStyle(i)}"></div><div class="item-title"><b>${esc(i.name)}</b><small>${esc(i.category)} · ${esc(i.unit)}</small></div><div class="item-actions">${editable?'<button class="edit" title="Изменить">✎</button>':''}${editable&&i.custom?'<button class="delete" title="Удалить">×</button>':''}</div></div><div class="values"><label>ДОЛЖНО БЫТЬ<input class="target" inputmode="decimal" type="number" min="0" step="0.001" value="${i.target??0}" ${editable?'':'disabled'}></label><label>ЕСТЬ СЕЙЧАС<input class="actual" inputmode="decimal" type="number" min="0" step="0.001" value="${i.actual??''}" placeholder="0" ${editable?'':'disabled'}></label><div class="diff">${missing(i)>0?`−${fmt(missing(i))} ${i.unit}`:'✓ хватает'}</div></div></article>`).join(''):'<div class="empty">Все позиции заполнены</div>');
  $('list').querySelectorAll('.item').forEach(card=>{const item=items.find(x=>x.id===card.dataset.id);card.querySelector('.target')?.addEventListener('input',e=>updateValue(item,'target',e.target.value));card.querySelector('.actual')?.addEventListener('input',e=>updateValue(item,'actual',e.target.value));card.querySelector('.edit')?.addEventListener('click',()=>openItemDialog(item));card.querySelector('.delete')?.addEventListener('click',()=>deleteItem(item));});
  const needs=items.filter(i=>missing(i)>0).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name)),unfilled=items.filter(i=>i.actual===null||i.actual==='').length;$('allCount').textContent=items.length;$('missingCount').textContent=needs.length;$('okCount').textContent=items.filter(i=>cleanNumber(i.target)>0&&missing(i)===0).length;$('unfilledCount').textContent=unfilled;$('remainsButton').classList.toggle('active',onlyUnfilled);$('needList').innerHTML=needHtml(needs);$('shiftCaption').textContent=editable?'Текущая смена':'Архив за выбранный день';$('shiftName').disabled=!editable;$('newShift').disabled=!editable;$('addItem').disabled=!editable;$('saveShift').disabled=!editable;}
function renderSummaryOnly(){document.querySelectorAll('.item').forEach(card=>{const i=items.find(x=>x.id===card.dataset.id);if(!i)return;card.classList.toggle('missing',missing(i)>0);card.querySelector('.diff').textContent=missing(i)>0?`−${fmt(missing(i))} ${i.unit}`:'✓ хватает';});const needs=items.filter(i=>missing(i)>0);$('missingCount').textContent=needs.length;$('okCount').textContent=items.filter(i=>cleanNumber(i.target)>0&&missing(i)===0).length;$('unfilledCount').textContent=items.filter(i=>i.actual===null||i.actual==='').length;$('needList').innerHTML=needHtml(needs);}
function updateValue(item,key,value){if(!isToday())return;item[key]=value===''?null:cleanNumber(value);queueDaySave();if(key==='target'){const cfg=configItems.find(i=>i.id===item.id);if(cfg)cfg.target=item.target;queueConfigSave();}if(onlyUnfilled&&key==='actual'&&value!=='')render();else renderSummaryOnly();}
function queueDaySave(){clearTimeout(dayTimer);$('saveStatus').textContent='Сохраняем в Firebase…';dayTimer=setTimeout(saveDay,350);}
function queueConfigSave(){clearTimeout(configTimer);configTimer=setTimeout(saveConfig,350);}
async function saveConfig(){if(applyingRemote)return;await setDoc(doc(db,'kitchen','config'),{items:configItems.map(i=>({...i,target:cleanNumber(i.target),actual:null})),updatedAt:serverTimestamp(),updatedBy:actor});}
async function saveDay(){if(applyingRemote||!isToday())return;try{await setDoc(doc(db,'kitchenDays',viewDay),{date:viewDay,items:items.map(snapshotItem),shiftName:$('shiftName').value||defaultShiftName(),updatedAt:serverTimestamp(),updatedBy:actor,editableUntil:nextMidnight()});$('saveStatus').textContent='Сохранено в Firebase · видно всем';setTimeout(()=>$('saveStatus').textContent='',1600);}catch(e){$('saveStatus').textContent=`Ошибка: ${e.message}`;}}
function mergeConfigIntoToday(){if(!isToday()||!items.length||!configItems.length)return;const old=new Map(items.map(i=>[i.id,i]));const merged=configItems.map(c=>({...c,actual:old.get(c.id)?.actual??null}));if(JSON.stringify(merged.map(snapshotItem))!==JSON.stringify(items.map(snapshotItem))){items=merged;queueDaySave();render();}}
async function initConfig(){const ref=doc(db,'kitchen','config'),snap=await getDoc(ref);if(!snap.exists()){const legacy=await getDoc(doc(db,'kitchen','current'));configItems=(legacy.exists()&&Array.isArray(legacy.data().items)?legacy.data().items:structuredClone(defaults)).map(i=>({...i,target:cleanNumber(i.target),actual:null}));await saveConfig();}configUnsub=onSnapshot(ref,s=>{if(!s.exists())return;configItems=s.data().items||structuredClone(defaults);mergeConfigIntoToday();});}
async function openDay(date){if(dayUnsub)dayUnsub();viewDay=date;$('viewDate').value=date;const ref=doc(db,'kitchenDays',date),snap=await getDoc(ref);if(!snap.exists()){if(date!==dayKey()){items=[];$('shiftName').value=`Нет записи за ${date}`;render();return;}const legacy=await getDoc(doc(db,'kitchen','current'));const legacyItems=legacy.exists()&&Array.isArray(legacy.data().items)?legacy.data().items:null;items=(legacyItems||configItems).map(i=>({...i,target:cleanNumber(i.target),actual:legacyItems?(i.actual??null):null}));$('shiftName').value=legacy.exists()?legacy.data().shiftName||defaultShiftName():defaultShiftName();await saveDay();}dayUnsub=onSnapshot(ref,s=>{if(!s.exists())return;applyingRemote=true;const data=s.data();items=data.items||[];$('shiftName').value=data.shiftName||'';render();applyingRemote=false;},e=>$('saveStatus').textContent=`Firebase: ${e.message}`);}
async function saveShift(){if(!isToday())return;const snapshot=items.map(i=>({...snapshotItem(i),actual:cleanNumber(i.actual),missing:missing(i)}));try{$('saveShift').disabled=true;$('saveStatus').textContent='Фиксируем смену…';await addDoc(collection(db,'kitchenShifts'),{items:snapshot,createdAt:serverTimestamp(),createdBy:actor,shiftName:$('shiftName').value,missingCount:snapshot.filter(i=>i.missing>0).length,date:viewDay});$('saveStatus').textContent='Смена сохранена навсегда и добавлена в историю.';await loadHistory();}catch(e){$('saveStatus').textContent=`Ошибка: ${e.message}`;}finally{$('saveShift').disabled=false;}}
function openItemDialog(item=null){$('itemId').value=item?.id||'';$('itemDialogTitle').textContent=item?'Изменить позицию':'Новая позиция';$('itemName').value=item?.name||'';$('itemCategory').value=item?.category||'Продукты';$('itemUnit').value=item?.unit||'кг';$('itemTarget').value=item?.target??0;$('itemDialog').showModal();}
function saveItemForm(){const id=$('itemId').value,name=$('itemName').value.trim();if(!name||!isToday())return;let item=id?items.find(i=>i.id===id):null;if(item){item.name=name;item.category=$('itemCategory').value;item.unit=$('itemUnit').value;item.target=cleanNumber($('itemTarget').value);const cfg=configItems.find(i=>i.id===id);if(cfg)Object.assign(cfg,item,{actual:null});else configItems.push({...item,actual:null});}else{item={id:`custom-${Date.now()}`,name,category:$('itemCategory').value,unit:$('itemUnit').value,target:cleanNumber($('itemTarget').value),actual:null,custom:true};items.push(item);configItems.push({...item,actual:null});}queueConfigSave();queueDaySave();render();}
function deleteItem(item){if(!isToday()||!confirm(`Удалить «${item.name}» из будущих смен?`))return;items=items.filter(i=>i.id!==item.id);configItems=configItems.filter(i=>i.id!==item.id);queueConfigSave();queueDaySave();render();}
async function loadHistory(){const snap=await getDocs(query(collection(db,'kitchenShifts'),orderBy('createdAt','desc'),limit(100)));history=snap.docs.map(d=>({id:d.id,...d.data()}));$('historySelect').innerHTML='<option value="">Выберите смену</option>'+history.map(h=>`<option value="${h.id}">${esc(h.date||'Без даты')} · ${esc(h.shiftName||'Смена')}</option>`).join('');}
function downloadPdf(){const h=history.find(x=>x.id===$('historySelect').value);if(!h||!window.pdfMake)return;const rows=[['Наименование','Должно','Было','Нужно']].concat(h.items.map(i=>[i.name,`${fmt(i.target)} ${i.unit}`,`${fmt(i.actual)} ${i.unit}`,i.missing>0?`${fmt(i.missing)} ${i.unit}`:'—']));window.pdfMake.createPdf({pageSize:'A4',pageMargins:[32,34,32,34],content:[{text:'TyuProduct — отчёт смены',style:'title'},{text:`Дата: ${h.date||'—'}\nСмена: ${h.shiftName||'—'}\nСформировано: ${new Date().toLocaleString('ru-RU')}`,margin:[0,4,0,16]},{table:{headerRows:1,widths:['*',65,65,65],body:rows},layout:'lightHorizontalLines'}],styles:{title:{fontSize:18,bold:true,color:'#0f766e'}},defaultStyle:{fontSize:9}}).download(`TyuProduct-${h.date||'shift'}.pdf`);}
function initShare(){const url='https://tyuzarplata-product.web.app';$('shareUrl').value=url;if(window.QRCode){new window.QRCode($('qrSmall'),{text:url,width:34,height:34,colorDark:'#0f403b',colorLight:'#ffffff',correctLevel:window.QRCode.CorrectLevel.M});new window.QRCode($('qrLarge'),{text:url,width:210,height:210,colorDark:'#0f403b',colorLight:'#ffffff',correctLevel:window.QRCode.CorrectLevel.H});}$('shareButton').onclick=()=>$('shareDialog').showModal();$('closeShare').onclick=()=>$('shareDialog').close();$('nativeShare').onclick=async()=>{if(navigator.share)await navigator.share({title:'TyuProduct',text:'Склад кухни TyuProduct',url});else{await navigator.clipboard.writeText(url);$('nativeShare').textContent='Ссылка скопирована';setTimeout(()=>$('nativeShare').textContent='Поделиться ссылкой',1200);}};}

async function main(){const config=await fetch('/__/firebase/init.json').then(r=>r.json());db=getFirestore(initializeApp(config));renderCategories();initShare();viewDay=dayKey();$('viewDate').max=viewDay;await initConfig();await openDay(viewDay);await loadHistory();$('search').oninput=render;$('onlyMissing').onchange=render;$('remainsButton').onclick=()=>{onlyUnfilled=!onlyUnfilled;if(onlyUnfilled){$('search').value='';$('onlyMissing').checked=false;category='Все';renderCategories();}render();};$('viewDate').onchange=e=>openDay(e.target.value);$('shiftName').oninput=queueDaySave;$('newShift').onclick=()=>{if(confirm('Начать новую смену? Нормы сохранятся, поля «Есть сейчас» очистятся.')){items.forEach(i=>i.actual=null);$('shiftName').value=defaultShiftName();queueDaySave();render();}};$('saveShift').onclick=saveShift;$('copyResult').onclick=async()=>{const lines=items.filter(i=>missing(i)>0).map(i=>`${i.name} — ${fmt(missing(i))} ${i.unit}`);await navigator.clipboard.writeText(lines.length?`НУЖНО ПОЛУЧИТЬ:\n${lines.join('\n')}`:'Всё в достатке');$('copyResult').textContent='Скопировано';setTimeout(()=>$('copyResult').textContent='Копировать',1200);};$('addItem').onclick=()=>openItemDialog();$('cancelItem').onclick=()=>$('itemDialog').close();$('itemForm').onsubmit=saveItemForm;$('historySelect').onchange=e=>$('downloadPdf').disabled=!e.target.value;$('downloadPdf').onclick=downloadPdf;}
main().catch(e=>{document.body.innerHTML=`<div class="empty">Ошибка Firebase: ${esc(e.message)}</div>`;});
